config/routes.rb
Place::Application.routes.draw do


  # 登入表單、登入動作、登出動作
  resources :users do
    resources :spaces
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :lots


  # 首頁
  root 'static_pages#home'


  match '/members', to: 'users#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="board">
  <div class="container">
    <div>
      <h1>雲端場地租借</h1>
      <h4>我們是全國場地租借系統，操作簡單又方便！</h4>
      <% if signed_in? %>
        <%= link_to '提供場地', new_user_space_path(current_user), class: 'fun_btn' %>
      <% else %>
        <%= link_to '提供場地', '#', class: 'fun_btn' %>
      <% end %>
      <span class="sep"></span>
      <%= link_to '我要租借', '#', class: 'fun_btn' %>
    </div>
  </div>
</div><!-- end board -->
<div class="container">
  <div class="fun_board">
    <h1 id="useful_6">六大好用功能</h1>
    <a href="#surf_pic" class="open featured" data-title="製作平面圖"><span class="fc"><i class="fa fa-th fa-3x"></i></span></a>
    <a href="#timing" class="featured" data-title="時間規劃"><span class="fc"><i class="fa fa-calendar fa-3x"></i></span></a>
    <a href="#easy_pay" class="featured" data-title="自由收費"><span class="fc"><i class="fa fa-usd fa-3x"></i></span></a>
    <a href="#easy_use" class="featured" data-title="簡單操作"><span class="fc"><i class="fa fa-ellipsis-h fa-3x"></i></span></a>
    <a href="#mapping" class="featured" data-title="地圖搜尋"><span class="fc"><i class="fa fa-globe fa-3x"></i></span></a>
    <a href="#dashboard" class="featured" data-title="後台管理"><span class="fc"><i class="fa fa-users fa-3x"></i></span></a>
  </div><!-- end fun_board -->

  <div class="fun_big_board">
    <div id="surf_pic">
      <div class="introo">
        <h1>刊登者</h1>
        <p>直覺地設計獨一無二的平面圖，刊登場地更簡單。</p>
        <h1>租借者</h1>
        <p>更容易看到刊登者的場地設計，平面圖一覽無遺。</p>
      </div>
      <div class="icoon"><i class="fa fa-th" style="font-size: 15em"></i></div>
    </div>
    <div id="timing" class="hidden">
      <div class="introo">
        <h1>刊登者</h1>
        <p>一隻手就能完成最完善的出租、時間設定，無痛規劃。</p>
        <h1>租借者</h1>
        <p>「可租借」、「已租借」、「審核中」…看清所有租借記錄！</p>
      </div>
      <div class="icoon"><i class="fa fa-calendar" style="font-size: 15em"></i></div>
    </div>
    <div id="easy_pay" class="hidden">
      <div class="introo">
        <h1>平台上就能夠完成交易</h1>
        <p>方便租借者的瀏覽系統、刊登者的自由收費系統</p>
      </div>
      <div class="icoon"><i class="fa fa-usd" style="font-size: 15em"></i></div>
    </div>
    <div id="easy_use" class="hidden">
      <div class="introo">
        <h1>刊登者</h1>
        <p>使用滑鼠就能完成最完善的場地設計，四大步驟完成刊登，簡單明瞭的操作，讓享受規劃的樂趣</p>
      </div>
      <div class="icoon"><i class="fa fa-ellipsis-h" style="font-size: 15em"></i></div>
    </div>
    <div id="mapping" class="hidden">
      <div class="introo">
        <h1>獨家過濾性搜尋</h1>
        <p>地圖區塊點擊設計，利用最簡單的方式找到您要的場地！</p>
      </div>
      <div class="icoon"><i class="fa fa-globe" style="font-size: 15em"></i></div>
    </div>
    <div id="dashboard" class="hidden">
      <div class="introo">
        <h1>刊登者</h1>
        <p>自由地刊登、下架、編輯場地。</p>
        <h1>租借者</h1>
        <p>簡易的下標匯款資訊，可與在線及時交流，讓交易更簡單。</p>
      </div>
      <div class="icoon"><i class="fa fa-users" style="font-size: 15em"></i></div>
    </div>
  </div>
</div>