config/routes.rb
Place::Application.routes.draw do


  # 登入表單、登入動作、登出動作
  resources :users do
    resources :spaces
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :lots


  # 首頁
  root 'static_pages#home'


  match '/members', to: 'users#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :lots
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = current_user.spaces
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @lots = current_user.spaces.find(params[:id]).lots
  end

  # GET /spaces/new
  def new


  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render action: 'show', status: :created, location: @space }
      else
        format.html { render action: 'new' }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :img, :is_rented, :user_id)
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :is_rented %><br>
    <%= f.check_box :is_rented %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th>Is rented</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.name %></td>
        <td><%= space.img %></td>
        <td><%= space.is_rented %></td>
        <td><%= space.user_id %></td>
        <td><%= link_to 'Show', user_space_path() %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<div class="container">
  <%= link_to '平面圖', '#sur-upload-or-make', class: 'sur_or_floor' %>
  <%= link_to '樓層圖', '#floor-upload-or-make', class: 'sur_or_floor' %>


  <div id="space_editor" style="display: none;">
    <ul id="sidebar">
      <a href="#" id="space_name" data-type="text" data-placement="right" data-title="自定名稱："><%= current_user.name %></a>的平面圖
    </ul>
    <div id="spaces_dumps"></div>
  </div>




</div>




<!-- model -->
<div id="sur-upload-or-make" style="display: none;">
  <p><a href="#" id="upload-sur-pic" onclick="$.fancybox.close();">上傳平面圖</a></p>
  <p><a href="#" id="make-sur-pic" onclick="$.fancybox.close();">製作平面圖</a></p>
</div>

app/views/spaces/show.html.erb
<div class="container">
  <button id="g"></button>
  <div id="space_editor">
    <% @lots.each do |lot| %>
      <p>
        <%= lot.name %>: <%= lot.pos_left %> : <%= lot.pos_top %>
      </p>
      <% if lot.pos_left.nil? and lot.pos_top.nil? %>
        <%= content_tag :div, "#{lot.name}", class: "#{lot.name} lot", id: "#{lot.id}" %>
      <% else %>
        <%= content_tag :div, "#{lot.name}", class: "#{lot.name} lot",
        style: " position: absolute; width: #{lot.width}px; height: #{lot.height}px; top: #{lot.pos_top}px; left: #{lot.pos_left}px; ", id: "#{lot.id}" %>
      <% end %>
    <% end %>
  </div>
</div>