config/routes.rb
Place::Application.routes.draw do


  # 登入表單、登入動作、登出動作
  resources :users do
    resources :spaces
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :lots


  # 首頁
  root 'static_pages#home'


  match '/members', to: 'users#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  belongs_to :space
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_action :set_lot, only: [:show, :edit, :update, :destroy]

  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
  end

  # GET /lots/new
  def new
    @lot = Lot.new
  end

  # GET /lots/1/edit
  def edit
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(lot_params)

    respond_to do |format|
      if @lot.save
        format.html { redirect_to @lot, notice: 'Lot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lot }
      else
        format.html { render action: 'new' }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1
  # PATCH/PUT /lots/1.json
  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot.destroy
    respond_to do |format|
      format.html { redirect_to lots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lot
      @lot = Lot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lot_params
      params.require(:lot).permit(:name, :width, :height, :pos_left, :pos_top, :space_id, :user_id)
    end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_for(@lot) do |f| %>
  <% if @lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% @lot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :pos_left %><br>
    <%= f.text_field :pos_left %>
  </div>
  <div class="field">
    <%= f.label :pos_top %><br>
    <%= f.text_field :pos_top %>
  </div>
  <div class="field">
    <%= f.label :space_id %><br>
    <%= f.number_field :space_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lots/edit.html.erb
<h1>Editing lot</h1>

<%= render 'form' %>

<%= link_to 'Show', @lot %> |
<%= link_to 'Back', lots_path %>

app/views/lots/index.html.erb
<h1>Listing lots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Width</th>
      <th>Height</th>
      <th>Pos left</th>
      <th>Pos top</th>
      <th>Space</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lots.each do |lot| %>
      <tr>
        <td><%= lot.name %></td>
        <td><%= lot.width %></td>
        <td><%= lot.height %></td>
        <td><%= lot.pos_left %></td>
        <td><%= lot.pos_top %></td>
        <td><%= lot.space_id %></td>
        <td><%= lot.user_id %></td>
        <td><%= link_to 'Show', lot %></td>
        <td><%= link_to 'Edit', edit_lot_path(lot) %></td>
        <td><%= link_to 'Destroy', lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lot', new_lot_path %>

app/views/lots/new.html.erb
<h1>New lot</h1>

<%= render 'form' %>

<%= link_to 'Back', lots_path %>

app/views/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lot.name %>
</p>

<p>
  <strong>Width:</strong>
  <%= @lot.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @lot.height %>
</p>

<p>
  <strong>Pos left:</strong>
  <%= @lot.pos_left %>
</p>

<p>
  <strong>Pos top:</strong>
  <%= @lot.pos_top %>
</p>

<p>
  <strong>Space:</strong>
  <%= @lot.space_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @lot.user_id %>
</p>

<%= link_to 'Edit', edit_lot_path(@lot) %> |
<%= link_to 'Back', lots_path %>