config/routes.rb
Place::Application.routes.draw do


  # 登入表單、登入動作、登出動作
  resources :users do
    resources :spaces
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :lots


  # 首頁
  root 'static_pages#home'


  match '/members', to: 'users#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>雲端場地租借</title>
    <!-- webfont -->
    <link href='http://fonts.googleapis.com/css?family=Candal' rel='stylesheet' type='text/css'>

    <!-- font awesome -->
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/css/jqueryui-editable.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/js/jqueryui-editable.min.js"></script>




  </head>
  <body>



    <!-- sign up form -->
    <div id="signup_form" style="display: none">
      <h1 align="center">註冊免費會員</h1>
      <%= form_for User.new, html: { class: 'main_sign_up_form' } do |f| %>
        <div>
          <p><%= f.text_field :name, placeholder: '名字' %></p>
          <p><%= f.email_field :email, placeholder: '電子郵件' %></p>
          <p><%= f.password_field :password, placeholder: '密碼', id: 'pw' %></p>
          <p><%= f.password_field :password_confirmation, placeholder: '確認密碼' %></p>
          <p>
            <%= f.submit '確認', class: 'btn' %>
          </p>
        </div>
      <% end %>
    </div>

    <!-- sign in form -->
    <div id="signin_form" style="display: none">
      <h1 align="center">登入網站</h1>
      <%= form_for :session, url: sessions_path, html: { class: 'main_sign_in_form' } do |f| %>
        <div>
          <p><%= f.email_field :email, placeholder: '電子郵件', class: 'required' %></p>
          <p><%= f.password_field :password, placeholder: '密碼', class: 'required' %></p>
          <p>
            <%= f.submit '登入', class: 'btn' %>
          </p>
        </div>
      <% end %>
    </div>


    <!-- navigation -->
    <div class="nav">
      <div class="container">
        <a href="/" id="logo"></a>


        <% if signed_in? %>

          <a href="#" data-dropdown="#dropdown-1" class="links user_drop">
            <span class="avatar"><%= gravatar_for current_user, size: 20 %></span>
            <%= current_user.name %>
          </a>

          <div id="dropdown-1" class="dropdown dropdown-tip">
            <ul class="dropdown-menu">
              <li><%= link_to '後台管理', current_user %></li>
              <li class="dropdown-divider"></li>
              <li><%= link_to '登出', signout_path, method: 'delete' %></li>
            </ul>
          </div>


        <% else %>

          <div class="links">
            <%= link_to '註冊', '#signup_form', class: 'main_form' %>
            <span class="item_sep">&nbsp;|&nbsp;</span>
            <%= link_to '登入', '#signin_form', class: 'main_form' %>
          </div>

        <% end %>

      </div>
    </div>

    <!-- message area -->
    <div class="container">
      <div class="messages">
        <% flash.each do |name, msg| %>
        <br>
          <div class="alert alert-<%= name %>">
            <!-- <button type="button" class="close" data-dismiss="alert">&times;</button> -->
            <%= msg %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- content area -->
    <div class="content">
      <%= yield %>
    </div>

    <!-- footer area -->
    <div class="footer">
      <div class="container">
        <!-- Copyright © 2013 Simpleplacing. All rights reserved. -->
      </div>
    </div>
  </body>
</html>